stages:
- name: 构建1
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  when:
    branch: {}
    event: {}
- name: 构建2
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: ls
  when:
    branch: {}
    event: {}
- name: 部署1
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch: {}
    event: {}
- name: 部署2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
