stages:
- name: "1"
  steps:
  - runScriptConfig:
      image: alpine
      shellScript: ls
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test
      pushRemote: true
      registry: 127.0.0.1:34083
timeout: 60
notification: {}
