stages:
- name: 111111111111111111111111ddddddddddddddddddd11
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hongxiaolu/test:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_STORAGE_PATH: /var/lib/docker2
      PLUGIN_TAG: test
  - runScriptConfig:
      image: docker:dind
      shellScript: ls
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demoapp
      registry: 127.0.0.1:34083
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch: {}
notification: {}
