apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-secret"
  labels:
    app: "{{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-secret"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.tenant.eurekaName }}
  username-eureka: {{ default "" .Values.tenant.eurekaName | b64enc | quote }}
  {{- else }}
  username-eureka: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.tenant.eurekaPassword }}
  password-eureka: {{ .Values.tenant.eurekaPassword | quote }}
  {{- else }}
  password-eureka: {{ randAlphaNum 10 | b64enc |quote }}
  {{- end }}
  {{- if .Values.tenant.mysqlUser }}
  MYSQL_USER: {{ .Values.tenant.mysqlUser | quote }}
  {{- else }}
  MYSQL_USER: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.tenant.mysqlPassword }}
  MYSQL_PASSWORD: {{ .Values.tenant.mysqlPassword | quote }}
  {{- else }}
  MYSQL_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}