kind: Service
apiVersion: v1
metadata:
  {{ if .Values.appointment.service.name -}}
  name: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    app: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
spec:
  type: {{ .Values.appointment.service.type }}
  ports:
    - port: {{ .Values.appointment.containerport }}
      targetPort: {{ .Values.appointment.containerport }}
    {{- if .Values.appointment.service.nodePort }}      
      nodePort: {{ .Values.appointment.service.nodePort }}
    {{- end }}
      protocol: TCP
  selector:
    app: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  {{ if .Values.appointment.service.name -}}
  name: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    app: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
{{ include "tenant.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
{{ include "tenant.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
{{ include "tenant.matchLabels" . | indent 8 }}
    spec:
      shareProcessNamespace: true
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }} 
      containers:
      - name: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-{{ .Values.appointment.service.name }}
        image: {{ .Values.appointment.image.repository }}:{{ .Values.appointment.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.appointment.containerport }}
          protocol: TCP
#        {{- if .Values.livenessProbe.enabled }}
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.livenessProbe.path }}
#            port: {{ .Values.livenessProbe.port }}
#          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
#         periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
#          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
#          successThreshold: {{ .Values.livenessProbe.successThreshold }}
#          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
#        {{- end }}
#        {{- if .Values.readinessProbe.enabled }}
#        readinessProbe:
#          httpGet:
#            path: {{.Values.readinessProbe.path }}
#            port: {{.Values.readinessProbe.port }}
#          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
#          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
#          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
#          successThreshold: {{ .Values.readinessProbe.successThreshold }}
#          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
#        {{- end }} 
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
#        - name: arrail-file
#          mountPath: /arrail/file
        env:
        - name: spring.profiles.active
          value: template
        envFrom: 
        - configMapRef:
            name: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-configmap
        - secretRef:
            name: {{ .Values.deployEnv }}-{{ .Values.tenant.tenantEnv}}-secret
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime
#      - name: arrail-file
#        persistentVolumeClaim:
#          claimName: arrail-file
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
